<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Anatomy" nsURI="http:///Anatomy.ecore" nsPrefix="Anatomy">
  <eClassifiers xsi:type="ecore:EClass" name="WorkPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//Type" defaultValueLiteral="Bugzilla"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" ordered="false"
        lowerBound="1" eType="#//State" defaultValueLiteral="UNKNOWN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="Bugzilla"/>
    <eLiterals name="WorkItem" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="PLANNED" value="1"/>
    <eLiterals name="ONGOING" value="2"/>
    <eLiterals name="DONE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Blocks">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  </eClassifiers>
</ecore:EPackage>
